config/routes.rb
Rails.application.routes.draw do

  get 'daily_sheet/index'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  resources :payment_details
  resources :payments
  get 'welcome/index'
  resources :footwears
  resources :sale_details
  resources :sales
  resources :way_pays
  resources :trademarks
  resources :clients
  resources :categories
  resources :release_countries
  resources :sizes
  resources :seasons
  resources :colors
  resources :providers

  get 'welcome/index/:day/:month/:year' => 'welcome#index'
  get 'welcome/index'

  get 'payments/new/:id' => 'payments#new'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  post 'get_retail_price/:id' => 'footwears#get_retail_price'

  post 'get_fees/:total' => 'way_pays#get_fees'

  post 'get_client_debt/:id' => 'clients#get_client_debt'

  post 'get_way_pay_interest/:id/:fee' => 'way_pays#get_way_pay_interest'

  post 'get_footwear_id/:sku' => 'footwears#get_footwear_id'



end

app/models/trademark.rb
class Trademark < ApplicationRecord
  belongs_to :provider
  has_many :client

  validates_presence_of :provider

  def to_s
  	name + " (" + provider.to_s + ")"
  end

end

app/controllers/trademarks_controller.rb
class TrademarksController < ApplicationController
  before_action :set_trademark, only: [:show, :edit, :update, :destroy]

  # GET /trademarks
  # GET /trademarks.json
  def index
    @trademarks = Trademark.all
  end

  # GET /trademarks/1
  # GET /trademarks/1.json
  def show
  end

  # GET /trademarks/new
  def new
    @trademark = Trademark.new
  end

  # GET /trademarks/1/edit
  def edit
  end

  # POST /trademarks
  # POST /trademarks.json
  def create
    @trademark = Trademark.new(trademark_params)

    respond_to do |format|
      if @trademark.save
        format.html { redirect_to @trademark, notice: 'Trademark was successfully created.' }
        format.json { render :show, status: :created, location: @trademark }
      else
        format.html { render :new }
        format.json { render json: @trademark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trademarks/1
  # PATCH/PUT /trademarks/1.json
  def update
    respond_to do |format|
      if @trademark.update(trademark_params)
        format.html { redirect_to @trademark, notice: 'Trademark was successfully updated.' }
        format.json { render :show, status: :ok, location: @trademark }
      else
        format.html { render :edit }
        format.json { render json: @trademark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trademarks/1
  # DELETE /trademarks/1.json
  def destroy
    @trademark.destroy
    respond_to do |format|
      format.html { redirect_to trademarks_url, notice: 'Trademark was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trademark
      @trademark = Trademark.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trademark_params
      params.require(:trademark).permit(:name, :description, :provider_id)
    end
end

app/helpers/trademarks_helper.rb
module TrademarksHelper
end

app/views/trademarks/_form.html.erb
<%= form_with(model: trademark, local: true) do |form| %>
  <% if trademark.errors.any? %>
    <script type="text/javascript">
      <% trademark.errors.full_messages.each do |message| %>
        toastr['error']('<%= message %>');
      <% end %>
    </script>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :provider_id %>
    <%= form.collection_select :provider_id, Provider.all, :id, :to_s, {prompt: "Seleccionar"}, {class: "select2 select-field"} %>
  </div>

  <div class="actions">
    <%= link_to 'Volver', :back, class: "btn btn-primary" %>
    <%= form.submit %>
  </div>
<% end %>

app/views/trademarks/edit.html.erb
<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <a href="/">Tablero</a>
  </li>
  <li class="breadcrumb-item">
    <a href="<%=trademarks_path%>">Marcas</a>
  </li>
  <li class="breadcrumb-item active">Editar Marca</li>
</ol>

<div class="container">
  <div class="card card-register mx-auto mt-5">
    <div class="card-header">Editar Marca</div>
    <div class="card-body">
      <%= render 'form', trademark: @trademark %>
    </div>
  </div>
</div>

app/views/trademarks/index.html.erb
<!-- Breadcrumbs-->
<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <a href="/">Tablero</a>
  </li>
  <li class="breadcrumb-item active">Marcas</li>

</ol>

<div class="card mb-3">
  <div class="card-header">
    <i class="fa fa-table"></i>
    Marcas</div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="datatable">
        <thead>
          <tr>
            <th>Nombre</th>
            <th>Proveedor</th>
            <th>Opciones</th>
          </tr>
        </thead>

        <tbody>
          <% @trademarks.each do |trademark| %>
            <tr>
              <td><%= trademark.name %></td>
              <td>
                <% if !trademark.provider.nil? %>      
                  <a href="/providers/<%= trademark.provider.id %>"><%= trademark.provider %></a>
                <% end %>
              </td>
              <td>
                <%= link_to((fa_icon "eye"), trademark) %>
                <%= link_to((fa_icon "pencil"), edit_trademark_path(trademark)) %>
                <%= link_to((fa_icon "trash-o"), trademark, method: :delete, data: { confirm: '¿Esta seguro que desea eliminar?' }) %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
</div>
<%= link_to 'Volver', :back, class: "btn btn-primary" %>
<%= link_to 'Crear Marca', new_trademark_path, class: 'btn btn-primary' %>

app/views/trademarks/new.html.erb
<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <a href="/">Tablero</a>
  </li>
  <li class="breadcrumb-item">
    <a href="<%=providers_path%>">Marcas</a>
  </li>
  <li class="breadcrumb-item active">Crear Marca</li>
</ol>

<div class="container">
  <div class="card card-register mx-auto mt-5">
    <div class="card-header">Crear Marca</div>
    <div class="card-body">
      <%= render 'form', trademark: @trademark %>
    </div>
  </div>
</div>

app/views/trademarks/show.html.erb
<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <a href="/">Tablero</a>
  </li>
  <li class="breadcrumb-item">
    <a href="<%=providers_path%>">Marcas</a>
  </li>
  <li class="breadcrumb-item active"><%= @trademark.name %></li>
</ol>

<div class="container">
  <div class="card card-register mx-auto mt-5">
    <div class="card-header"><%= @trademark.name %></div>
    <div class="card-body">
    	<p>
		  <strong>Nombre:</strong>
		  <%= @trademark.name %>
		</p>

		<p>
		  <strong>Proveedor:</strong>
		  <%= @trademark.provider %>
		</p>
		<div class="text-center">
      <%= link_to 'Volver', :back, class: "btn btn-primary" %>
			<%= link_to 'Editar', edit_trademark_path(@trademark), class: "btn btn-primary" %>
		</div>
    </div>
  </div>
</div>